[project]
authors = ["Lev <lev@example.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "Lev_N"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
imageio = ">=2.35.1,<3"
ipykernel = ">=6.29.5,<7"
argopy = ">=0.1.16,<0.2"
matplotlib = ">=3.9.2,<4"
erddapy = ">=2.2.0,<3"
cartopy = ">=0.23.0,<0.24"
