[project]
authors = ["Robert Ford <rford2@albany.edu>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "ohw24_proj_north_atlantic_variability_us"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
xeofs = ">=2.4.0,<3"
intake = ">=0.7.0,<0.8"
intake-esm = ">=2024.2.6,<2025"
ipykernel = ">=6.29.5,<7"
xrft = ">=1.0.1,<2"
argopy = ">=0.1.16,<0.2"
pip = ">=24.2,<25"
s3fs = ">=2024.6.1,<2025"
geoviews = ">=1.12.0,<2"
gcsfs = ">=2024.6.1,<2025"
nc-time-axis = ">=1.4.1,<2"
pycwt = ">=0.3.0a22,<0.4"
multitaper = ">=1.2.0,<2"
